### PR TITLE
chore: update Desktop Modeler screenshots to v5.16.0

### PR DESCRIPTION
**Pull request by nikku**

### CODE REVIEW

**Comment by tmetzke** [comment]
@nikku, the Spring guide images now reside in `get-started/content/archive/spring/img`. Can you fix this on your scripts' end? 🙂

**Comment by tmetzke** [comment]
You can also ignore updating them, if you like. We don't adjust the guides in the archives anymore.

**Comment by nikku** [comment]
We'd rather ignore them, if that is fine for you.

**Comment by tmetzke** [comment]
> We'd rather ignore them, if that is fine for you.

Absolutely 👍

**Comment by tmetzke** [comment]
@nikku, just to make sure this doesn't become stale: Do you need anything from our end or will you adjust your team's script and adjust the PR here accordingly? 🙂

**Comment by nikku** [comment]
We have https://github.com/camunda/camunda-docs-modeler-screenshots/issues/53 and it is also in our spring cleaning backlog :crossed_fingers:.

**Comment by nikku** [comment]
I'll close this PR.

**Comment by nikku** [comment]
We fixed this, so the update is no longer happening, cf. https://github.com/camunda/camunda-docs-modeler-screenshots/pull/68.

**Comment by tmetzke** [comment]
> We fixed this, so the update is no longer happening, cf. [camunda/camunda-docs-modeler-screenshots#68](https://github.com/camunda/camunda-docs-modeler-screenshots/pull/68).

Should the quickstart guide still be updated? That was also part of this PR initially and would still be in the future (for now).

**Comment by nikku** [comment]
Depends on how you like it. For now we continue to update it, and just removed the spring bits.

**Pull request closed without merging**
