### PR TITLE
chore(release): set 7.21 as default version

### PR DESCRIPTION
**Pull request by danielkelemen**

### CODE REVIEW

**Comment by danielkelemen** [comment]
Will be merged on the release day.

**Review by mboskamp — COMMENTED** [review]
❓ I think we also need to adjust the [stage .htaccess](https://github.com/camunda/camunda-docs-static/blob/59891177af3a9b5bdf49814762aec6779c53f8b9/config/stage/.htaccess). Is this done with another ticket?

**Comment by danielkelemen** [comment]
@mboskamp I was just thinking about that too.
Our guide only said to update the Javadoc rule, I already did that: https://github.com/camunda/camunda-docs-static/commit/937b2f65d548919a5bf770209161a4bb746ccf72
But I guess the rest of the file should also be updated to 22 at some point, right?

**Comment by mboskamp** [comment]
Maybe the guide can be improved. If you look at the history of the stage .htaccess file, I think we need to adjust all of it.
* https://github.com/camunda/camunda-docs-static/commit/76b0c55d5bda307ab786c9ecb36fbddfa3c3795f
* https://github.com/camunda/camunda-docs-static/commit/574e604d81d82111b47780f4294028f9f4d9c745

**Comment by danielkelemen** [comment]
I'll open a separate PR for that and update the guide for the stage file.

**Review by mboskamp — APPROVED** [review]

**Pull request merged**
