### PR TITLE
chore(download): Improve download page

### PR DESCRIPTION
**Pull request by felix-mueller**

### CODE REVIEW

**Comment by meyerdan** [comment]
👍 from my side @romansmirnov who can merge this?

**Comment by romansmirnov** [comment]
@koevskinikola can do this!

**Comment by koevskinikola** [comment]
Hey Felix,

I added your contributions to master. We'll release the changes together with the Camunda BPM 7.10 release at the end of the week.

Cheers,
Nikola

**Comment by felix-mueller** [comment]
Hi Nikola,
perfect, thanks a lot!
Best
Felix

**Pull request closed without merging**
