### PR TITLE
Support jira changes

### PR DESCRIPTION
**Pull request by garima-camunda**
This commit contains the changes in JIRA for customers, due to upcoming JIRA migration on 11th Feb.

### CODE REVIEW

**Comment by tasso94** [comment]
Hi @garima-camunda, is this a duplicate of #433?

**Comment by garima-camunda** [comment]
Yes, sorry it is. Should I close it?

**Comment by tasso94** [comment]
@garima-camunda, Yes please. :)

**Comment by garima-camunda** [comment]
Closed this PR as duplicate of https://github.com/camunda/camunda-docs-static/pull/433

**Pull request closed without merging**
