### PR TITLE
chore(release): set 7.19 as default version

### PR DESCRIPTION
**Pull request by yanavasileva**
https://github.com/camunda/camunda-bpm-platform/issues/2938

### CODE REVIEW

**Review by mboskamp — CHANGES_REQUESTED** [review]
The file for `live` looks good.
:x: What about the [.htaccess file](https://github.com/camunda/camunda-docs-static/blob/7.19-release/config/stage/.htaccess) for `stage`? I think we should update this one too.

**Comment by yanavasileva** [comment]
I adjusted the stage file as well in 97040fe.

**Review by mboskamp — APPROVED** [review]
👍

**Comment by mboskamp** [comment]
Before releasing the docs, we can check the redirects on stage.

**Pull request merged**
