### PR TITLE
CAM-14617: update theme for download box

### PR DESCRIPTION
**Pull request by ThorbenLindhauer**
- informs users about EE license and third-party libraries
  in the download box

related to CAM-14617

### CODE REVIEW

**Review by tasso94 — CHANGES_REQUESTED** [review]
Your commit adds the assets `docs.css` and `docs.js` without minification. This increases their size and slows down page loading. 

How did you generate them? `grunt publish` should do the trick.

**Comment by ThorbenLindhauer** [comment]
Thanks for sharing, will do that. Had no idea how to create a minified theme. I'll add it to the docs theme readme, too.

**Comment by ThorbenLindhauer** [comment]
I have clarified the theme readme here: https://github.com/camunda/camunda-docs-theme/commit/c95def255c4cfcd75144b16dc1eeb61dd5bc54d8

**Review by tasso94 — APPROVED** [review]
Looks good to me and works! 👍

**Pull request merged**
