### PR TITLE
7.15 release java

### PR DESCRIPTION
**Pull request by tmetzke**
related to CAM-13218

### CODE REVIEW

**Review by koevskinikola — APPROVED** [review]
Looks good. The first screenshot here https://docs.camunda.org/get-started/java-process-app/model/#create-a-new-bpmn-diagram can also be updated. The modeler doesn't support CMMN anymore. But this is a minor, optional thing, and I doubt that it impacts the guide.

**Comment by tmetzke** [comment]
Thanks @koevskinikola, I also noticed that in some other places actually, now that you mentioned it. I was wondering if we could use something similar to https://github.com/camunda/camunda-bpm-dev-docs/blob/master/howtos/update-screenshots.md to do such a thing in one sweep.

**Comment by koevskinikola** [comment]
I guess it can be automated, although, we would need to also automate the `fixup` process as well. Or did you mean something just for obtaining the screenshots?

**Comment by tmetzke** [comment]
Probably just the screenshots for starters but we can discuss this offline 😃 
I will merge this as-is right now as I think the screenshots are still OK as they are, although CMMN is still visible.

**Pull request merged**
