### PR TITLE
chore(download): add optimize 3.11.0-alpha4 to download page

### PR DESCRIPTION
**Pull request by cigdemilhan**

### CODE REVIEW

**Review by RomanJRW — CHANGES_REQUESTED** [review]
Let's just have the latest alpha please 🙂

**Review by misiekhardcore — APPROVED** [review]
LGTM

**Comment by misiekhardcore** [comment]
@RomanJRW I will make a separate PR to change the text above and keep only the latest alpha, WDYT?

**Comment by misiekhardcore** [comment]
made OPT-7176 to modify the page to only show latest alpha

**Pull request merged**
